version: '3.3'
services:
   jenkins:
     image: aryandvn24/jenkinsmod
     privileged: true
     user: root
     ports:
       - 8080:8080
       - 50000:50000
     container_name: jenkins
     volumes:
       - Jenkins:/var/jenkins_home
       - /var/run/docker.sock:/var/run/docker.sock

   nexus:
     image: aryandvn24/aryan-nexus
     privileged: true
     user: root
     ports:
       - 8081:8081
     container_name: nexus
     volumes:
       - Nexus:/nexus-data

   sonarqube:
     container_name: sonarqube
     image: sonarqube
     depends_on:
       - sonarqube-database
     volumes:
       - sonarqube_conf:/opt/sonarqube/conf
       - sonarqube_data:/opt/sonarqube/data
       - sonarqube_extensions:/opt/sonarqube/extensions
       - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
     ports:
       - 9000:9000
       
   sonarqube-database:
     container_name: sonarqube-database
     image: aryandvn24/aryan-pdb
     environment:
       POSTGRES_USER: aryandvn
       POSTGRES_PASSWORD: root
       POSTGRES_DB: mydb
     volumes:
       - sonarqube_database:/var/lib/postgresql
       - sonarqube_database_data:/var/lib/postgresql/data
     ports:
       -   5432:5432

   db:
     image: mysql:5.7
     volumes:
       - db_vol:/var/lib/mysql
       - ./mysql-dump:/docker-entrypoint-initdb.d
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: testdb1
       MYSQL_USER: testuser
       MYSQL_PASSWORD: root
     ports:
       - 3306:3306
   phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - '8083:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
   web:
    build:
      context: .       
    depends_on:
      - db
    image: tomcat
    volumes:
      - ./target/LoginWebApp-1.war:/usr/local/tomcat/webapps/LoginWebApp-1.war
    ports:
      - '8082:8080'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb1
      MYSQL_USER: testuser
      MYSQL_PASSWORD: root
volumes:
    db_vol:
      external: true      
    Nexus:
      external: true
    Jenkins:
      external: true
    sonarqube_database_data:
      external: true
    sonarqube_bundled-plugins:
      external: true
    sonarqube_conf:
      external: true
    sonarqube_data:
      external: true
    sonarqube_database:
      external: true
    sonarqube_extensions:
      external: true

